# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/clojure:lein-2.7.1-browsers

  environment:
        LEIN_ROOT: "true"
        # Customize the JVM maximum heap limit
        JVM_OPTS: -Xmx3200m


version: 2
jobs:
  test:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: lein deps

      - run:
          name: Build JS
          command: lein cljsbuild once test

      - run:
          name: Run CLJS tests
          command: lein doo once

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test